### ISSUE TITLE
Not providing the current time is deprecated. Please pass an instance of DateTimeInterface.

### ISSUE THREAD

**Issue by savanihd** [GeneaLabs/laravel-sign-in-with-apple#35]
Getting following error Can you help?
"Not providing the current time is deprecated. Please pass an instance of DateTimeInterface."

![Whoops-There-was-an-error-](https://user-images.githubusercontent.com/6205405/115546435-a88b7900-a2c2-11eb-80a8-2ad66ce5161d.png)

**Comment by mikebronner** [comment]
Hi @savanihd, could you provide the full stack trace found in your `laravel.log` file for this error? Thanks!

**Comment by savanihd** [comment]
i found following log file error:
```
[2021-04-22 10:28:48] production.ERROR: Not providing the current time is deprecated. Please pass an instance of DateTimeInterface. {"exception":"[object] (ErrorExcepti$
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(16384, 'Not providing t...', '/home/forge/cir...', 299, Array)
#1 /home/forge/circles-crm.zoowho.com/vendor/lcobucci/jwt/src/Token.php(299): trigger_error('Not providing t...', 16384)
#2 /home/forge/circles-crm.zoowho.com/vendor/socialiteproviders/apple/Provider.php(135): Lcobucci\\JWT\\Token->isExpired()
#3 /home/forge/circles-crm.zoowho.com/vendor/socialiteproviders/apple/Provider.php(111): SocialiteProviders\\Apple\\Provider::verify('eyJraWQiOiI4NkQ...')
#4 /home/forge/circles-crm.zoowho.com/vendor/socialiteproviders/apple/Provider.php(169): SocialiteProviders\\Apple\\Provider->getUserByToken('eyJraWQiOiI4NkQ...')
#5 /home/forge/circles-crm.zoowho.com/app/Http/Controllers/User/SocialController.php(127): SocialiteProviders\\Apple\\Provider->user()
#6 [internal function]: App\\Http\\Controllers\\User\\SocialController->handleWebLoginAppleCallback(Object(Illuminate\\Http\\Request))
#7 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#8 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handleW$
#9 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illumin$
#10 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#11 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#12 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Obj$
#13 /home/forge/circles-crm.zoowho.com/vendor/laravel/passport/src/Http/Middleware/CreateFreshApiToken.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{clo$
#14 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laravel\\Passport\\Http\\Middleware\\CreateFreshApiToken->han$
#15 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#16 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\$
#17 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(O$
#18 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#19 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illumi$
#20 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->ha$
#21 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#22 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate$
#23 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle($
#24 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#25 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routi
#26 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object($
#27 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#28 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illu$
#29 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->h$
#30 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#31 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Rout$
#32 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object$
#33 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#34 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}$
#35 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#36 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illumina$
#37 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\R$
#38 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\$
#39 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\$
#40 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\H$
#41 /home/forge/circles-crm.zoowho.com/vendor/beyondcode/laravel-query-detector/src/QueryDetectorMiddleware.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\$
#42 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): BeyondCode\\QueryDetector\\QueryDetectorMiddleware->handle(Ob$
#43 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#44 /home/forge/circles-crm.zoowho.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\$
#45 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Htt$
#46 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#47 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illu$
#48 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->$
#49 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#50 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illu$
#51 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->$
#52 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#53 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illum$
#54 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->h$
#55 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#56 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline$
#57 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenance$
#58 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}$
#59 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}
#60 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /home/forge/circles-crm.zoowho.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThrough$
#62 /home/forge/circles-crm.zoowho.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#63 {main}
"}
```

**Comment by mikebronner** [comment]
Hi @savanihd, thank you for providing the traceback. It appears you are using the SocialiteProviders package with Apple Sign On package. This package does not work with the SocialiteProviders package. It is far more likely you are using their Apple Sign On package instead. If you believe that's not the case, could you paste your `composer.json` file here?

Thanks!

**Comment by mikebronner** [comment]
Closing for now, unless further information is provided. I'll be happy to reopen at that point. :)

**Comment by savanihd** [comment]
This is my composer packages lists:
```
 "require": {
      "php": "^7.2.5",
      "alymosul/laravel-exponent-push-notifications": "^2.1",
      "arcanedev/log-viewer": "~4.7.0",
      "aws/aws-sdk-php": "~3.0",
      "barryvdh/laravel-ide-helper": "^2.6",
      "benwilkins/laravel-fcm-notification": "dev-master",
      "bkwld/cloner": "^3.9",
      "cvsouth/eloquent-inheritance": "1.0.5",
      "doctrine/dbal": "2.9",
      "fideloper/proxy": "^4.0",
      "fruitcake/laravel-cors": "^2.0",
      "guzzlehttp/guzzle": "^6.3",
      "hexatex/abstractenum": "dev-master",
      "intervention/image": "^2.5",
      "laravel-validation-rules/phone": "^1.1",
      "laravel/framework": "5.8.*",
      "laravel/passport": "^7.3",
      "laravel/scout": "^6.1",
      "laravel/socialite": "^4.2",
      "laravel/tinker": "^1.0",
      "laravelcollective/html": "^5.8",
      "lcobucci/jwt": "^3.4",
      "league/flysystem-aws-s3-v3": "~1.0",
      "league/fractal": "^0.17.0",
      "maatwebsite/excel": "^3.1",
      "php-ffmpeg/php-ffmpeg": "^0.14.0",
      "php-imap/php-imap": "^4.1",
      "santigarcor/laratrust": "5.2.*",
      "silber/bouncer": "v1.0.0-rc.5",
      "socialiteproviders/apple": "^3.0",
      "spatie/laravel-query-builder": "^1.16",
      "teamtnt/laravel-scout-tntsearch-driver": "^6.1",
      "thujohn/twitter": "^2.3",
      "tightenco/parental": "~0.7",
      "troelskn/laravel-fillable-relations": "dev-master",
      "yajra/laravel-datatables": "^1.5"
   },
```

**Comment by mikebronner** [comment]
Hi @savanihd, yes, you are using the Socialite Providers version, not this one. Best to open the issue there. Best of luck!
